### ISSUE TITLE
デフォルトの位置にBVEがインストールされていたら、そこを既定値として表示してほしい

### ISSUE THREAD

**Issue by TetsuOtter** [automatic9045/AtsEX.Setup#1]
## 概要

インストーラでBVEの実行ファイル位置を選択する箇所にて、初期値が「未選択」になっていますが、これを「BVEのインストーラでインストールした際のデフォルトの位置」に変更してほしいです。

もちろん、その場所にファイルが無かった場合は「未選択」状態になってもいいと思います。

## きっかけ

インストーラでBVE5/6の実行ファイル位置を検出する方法は「開いているプロセスからBVEを探す」という動作になっているかと思われます。
加えて、

今回、BVEを起動した際にアップデートのお知らせが出たため、「ダウンロード」ボタンを押してダウンロードを行い、インストーラを実行しました。

インストーラの手順のひとつに「BVEの実行ファイルがある場所を選択する」というものがあり、そこでは「手動選択」と「自動選択」みたいな選択肢があり、「自動選択」を押下すると「現在実行中のプロセスからBVEを探す」処理が走ります。
しかし、アップグレードの際に対象のプロセスを終了しておく癖がついてしまっていて、結局インストーラを実行する頃にはBVEを既に閉じてしまっていました。
わざわざそのためだけにBVEを起動するのは面倒ですし、結局「手動選択」にて実行ファイルを選んだのですが、ファイル選択ダイアログのデフォルトが「デスクトップ」になっているため、`C:\Program Files\mackoy\...` と移動するのがとても手間に感じました。

## 期待する動作

BVEの実行ファイル位置のデフォルト値について、

- `C:\Program Files\mackoy\BveTs6\BveTs.exe` (BVE5は `C:\Program Files (x86)\mackoy\BveTs5\BveTs.exe`) に実行ファイルが存在する場合は、そのパス
- それ以外の場合は「未選択」のまま

## その他

シナリオフォルダのパスもBVEの設定を読んでデフォルト値を設定してほしいですが、BVE5とBVE6で設定が競合した際にどうするかが問題になるため、別のIssueにしてしまっていいと思っています。

**Comment by automatic9045** [comment]
AtsEX のインストーラーに関してはリポジトリを分離してありまして……
折角書いてくださったところ大変恐縮なのですが、コミットと Issue の関連付けなどの都合で、そちらのリポジトリで Issue を再度投稿していただけると嬉しいです🙇

https://github.com/automatic9045/AtsEX.Setup

**Comment by TetsuOtter** [comment]
@automatic9045 失礼しました 🙇 
再度投稿するよりも、IssueのTransfer機能を使った方が良いように思うのですが、いかがでしょう…?

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by automatic9045** [comment]
そんな機能があったとは……！今試してみましたが、便利ですねこれ。ご教示ありがとうございます。

さて。
本題ですが、確かに BVE がインストールされる場所はデフォルトでは固定ですから、確かに初めから指定してしまうこともできますね！次バージョンからそうしようと思います。

ちなみに、

> ファイル選択ダイアログのデフォルトが「デスクトップ」になっているため、C:\Program Files\mackoy\... と移動するのがとても手間に感じました。

初期位置をデスクトップに指定しているのは、「大体デスクトップにショートカットが置いてあるだろうから、一番手軽で便利なのではないか」と考えたからだったりします。
ただ自動で指定できるのならそちらの方が圧倒的に良いですね。

**Comment by TetsuOtter** [comment]
> 大体デスクトップにショートカットが置いてあるだろうから、

確かに…!  いつもデスクトップショートカット使ってないので、完全に忘れてました…

ありがとうございます 🙇 よろしくお願いします。

**Comment by automatic9045** [comment]
実装しました。→ 0632ad4673c5517765c25cf9d727ecbf55809c39

> ## その他
> シナリオフォルダのパスもBVEの設定を読んでデフォルト値を設定してほしいですが、BVE5とBVE6で設定が競合した際にどうするかが問題になるため、別のIssueにしてしまっていいと思っています。

折衷案として、ひとまず `%USERPROFILE%\Documents\BveTs\Scenarios\` が存在するならば既定値として使用する仕様にしました。→ e1040b74213e14f475c30a90aae00305202eeef8
シナリオフォルダを変更する層＝「パスを指定してください」と言われて意味が理解できる層、だと思うので。いかがでしょうか？

本日中にリリース予定のAtsEX ver1.0-RC6のパッケージにて、これらの変更を適用したインストーラーを使用しますので、宜しければそちらで動作の様子を確認してみていただければと思います。

**Comment by automatic9045** [comment]
@TetsuOtter 現行の仕様でいかがでしょうか？良さそうでしたらCloseしちゃいます～

**Comment by TetsuOtter** [comment]
ごめんなさい…時間取れてなくて確認できてないです…

コメント頂いた仕様でバッチリだと思います！
次の日曜に使ってみて確認します🙏

**Comment by automatic9045** [comment]
承知しました！では一応日曜日までは閉じずに残しておきますね

**Comment by TetsuOtter** [comment]
@automatic9045 すみません…遅くなりました…
BVEインストールディレクトリについては問題ないと思います！ありがとうございます！
(欲を言うと、自動検出の場合は末尾に `(自動検出)` みたいに書いてあるとわかりやすそうです)

ただ、シナリオディレクトリについて、なぜかSenariosが存在しないはずなのにそこが初期表示されました…
![image](https://github.com/automatic9045/AtsEX.Setup/assets/31824852/2d541da1-f856-4def-89c5-9f66b55a2485)

そのまま続行しようとすると、さすがに「ディレクトリが存在しません」と出ました。
![image](https://github.com/automatic9045/AtsEX.Setup/assets/31824852/cf4ce436-0eb3-4beb-976f-80bd622dcbc0)

---

BVE5の実行ファイル名を変えて試したところ、それは正常に未選択状態でした。なので、シナリオフォルダ検出だけの問題になるかなと思います。
お手数おかけしますが、確認をお願いいたします :pray:

**Comment by automatic9045** [comment]
検証ありがとうございます！

> (欲を言うと、自動検出の場合は末尾に (自動検出) みたいに書いてあるとわかりやすそうです)

実装しました。→ d6f638529af4a1e32a03028add63c6f38d7363e8

> ただ、シナリオディレクトリについて、なぜかSenariosが存在しないはずなのにそこが初期表示されました…

既定のシナリオディレクトリは強制的に生成されるので環境関わらず存在するものと思っていたのですが、削除することも可能なのですね🤔
存在しない場合は指定されないように変更しました。→ e28061f868e7f828f25d98589a9694e9a29d31b0

こちらの変更を適用したコンパイル済ファイルを準備しましたので、想定されている動作になっているかどうか、お時間のある時に再度ご確認いただけますでしょうか🙇‍♂️
https://drive.google.com/file/d/1Kjnsp6I9s5robET11GxQFijzp49INihK/view?usp=sharing

**Comment by TetsuOtter** [comment]
> 検証ありがとうございます！
> 
> > (欲を言うと、自動検出の場合は末尾に (自動検出) みたいに書いてあるとわかりやすそうです)
> 
> 実装しました。→ [d6f6385](https://github.com/automatic9045/AtsEX.Setup/commit/d6f638529af4a1e32a03028add63c6f38d7363e8)
> 
> > ただ、シナリオディレクトリについて、なぜかSenariosが存在しないはずなのにそこが初期表示されました…
> 
> 既定のシナリオディレクトリは強制的に生成されるので環境関わらず存在するものと思っていたのですが、削除することも可能なのですね🤔 存在しない場合は指定されないように変更しました。→ [e28061f](https://github.com/automatic9045/AtsEX.Setup/commit/e28061f868e7f828f25d98589a9694e9a29d31b0)
> 
> こちらの変更を適用したコンパイル済ファイルを準備しましたので、想定されている動作になっているかどうか、お時間のある時に再度ご確認いただけますでしょうか🙇‍♂️ https://drive.google.com/file/d/1Kjnsp6I9s5robET11GxQFijzp49INihK/view?usp=sharing

遅くなりました🙇🙇🙇
RC7にて動作確認できました！ありがとうございます！！！
